function survey2 = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  SURVEY2 = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  SURVEY2 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  survey2 = importfile("C:\Users\dkelly\Documents\MATLAB\m508_final_project\survey2.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 22-Apr-2020 20:41:36

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 13);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["y", "robot_replacement", "climate_change", "transformers_movies", "scientists", "vaccines", "books", "ghosts", "research_pct", "adequate_funds", "sun", "smart", "shower"];
opts.VariableTypes = ["categorical", "categorical", "categorical", "double", "categorical", "categorical", "double", "categorical", "double", "categorical", "categorical", "categorical", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["y", "robot_replacement", "climate_change", "scientists", "vaccines", "ghosts", "adequate_funds", "sun", "smart", "shower"], "EmptyFieldRule", "auto");

% Import the data
survey2 = readtable(filename, opts);

end